dat<-read.table(file="Data.txt", sep=",")
y<-t(dat)
a<-table(y)
f<-as.data.frame(a)
f[,3]<-100*a/(sum(a))
f[,4]<-cumsum(a)
f[,5]<-cumsum(f[,3])
colnames(f)<-c("value","frequency","frequency","cumulative frequency", "accumulated frequency")
d<-as.numeric(y)
v<-sort(d)
x<-unique(v)
y<-as.numeric(f[,4])
plot(a,type="l",main="frequency range",xlab="value", ylab="frequency")
plot(x,as.numeric(f[,4]),type="l",xlab="value",ylab="frequency range", main= "absolute frequency cumulate")
plot(x,as.numeric(f[,5]),type="l",xlab="value",ylab="frequency range", main= "accumulated frequency")
f